[tox]
envlist = py311, py312, py313, py314
isolated_build = true

[testenv]
runner = uv-venv-lock-runner
description = run tests
extras =
    dev
commands =
    pytest {posargs}

[testenv:lint]
runner = uv-venv-lock-runner
description = lint check (no changes)
extras =
    dev
commands =
    ruff check

[testenv:fix]
runner = uv-venv-lock-runner
description = lint with auto-fix
extras =
    dev
commands =
    ruff check --fix

[testenv:ty]
runner = uv-venv-lock-runner
description = dev environment
extras =
    dev
commands =
    ty check

[testenv:dev]
runner = uv-venv-lock-runner
description = dev environment
extras =
    dev
commands =
    pytest