[tox]
envlist = py310, py311, py312, py313
isolated_build = true

[testenv]
runner = uv-venv-lock-runner
description = run tests
extras =
    dev
commands =
    pytest {posargs}

[testenv:lint]
runner = uv-venv-lock-runner
description = dev environment
extras =
    dev
commands =
    ruff check --fix

[testenv:ty]
runner = uv-venv-lock-runner
description = dev environment
extras =
    dev
commands =
    ty check

[testenv:dev]
runner = uv-venv-lock-runner
description = dev environment
extras =
    dev
commands =
    pytest