name: Test strongbus

jobs:
    test:
        name: python
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v6

            - name: Install tox-uv
              run: uv tool install tox --with tox-uv

            - name: run tox
              run: tox
            
            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v5
              with:
              token: ${{ secrets.CODECOV_TOKEN }}

      